from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView
from .views import (
    RegisterView, VerifyEmailView, ResendVerificationView, LoginView, PasswordResetRequestView,
    PasswordResetConfirmView, ProfileView, LogoutView, SocialLoginView,
    SocialProvidersStatusView,
    FacebookRedirectView, InstagramRedirectView, SocialLoginCallbackView,
    MediaListView, MediaUploadView, MediaDeleteView, MediaBulkDeleteView,
    MyUploadsView,
    MediaModerationView, MediaModerateSingleView, MediaFileView,
    PublicMediaListView, PublicUserListView, PublicUserDetailView,
    UserProfilePictureView,
    AdminDashboardView, AdminSettingsView,
    AdminUserListView, AdminUserDetailView, AdminUserToggleStaffView,
    AdminUserBulkUpdateView,
    MediaBulkModerationView, TaskStatusView, FaceGroupListView, FaceTagListView, FaceTagDetailView,
    CookieConsentView,
    CustomTokenRefreshView,
    MediaDetectFacesView,
    DeleteAllFacesView,
)

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('verify-email/', VerifyEmailView.as_view(), name='verify-email'),
    path('resend-verification/', ResendVerificationView.as_view(), name='resend-verification'),
    path('login/', LoginView.as_view(), name='login'),
    path('password-reset/', PasswordResetRequestView.as_view(), name='password-reset'),
    path('password-reset-confirm/<str:uidb64>/<str:token>/', PasswordResetConfirmView.as_view(), name='password-reset-confirm'),
    path('token/refresh/', CustomTokenRefreshView.as_view(), name='token_refresh'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('social/login/', SocialLoginView.as_view(), name='social-login'),
    path('social/status/', SocialProvidersStatusView.as_view(), name='social-providers-status'),
    path('social/facebook/', FacebookRedirectView.as_view(), name='social-facebook'),
    path('social/instagram/', InstagramRedirectView.as_view(), name='social-instagram'),
    path('social/callback/', SocialLoginCallbackView.as_view(), name='social-login-callback'),
    path('media/', MediaListView.as_view(), name='media-list'),
    path('media/upload/', MediaUploadView.as_view(), name='media-upload'),
    path('media/upload/status/<str:task_id>/', TaskStatusView.as_view(), name='upload-task-status'),
    path('media/<int:media_id>/', MediaDeleteView.as_view(), name='media-delete'),
    path('media/bulk-delete/', MediaBulkDeleteView.as_view(), name='media-bulk-delete'),
    path('media/my-uploads/', MyUploadsView.as_view(), name='my-uploads'),
    path('media/moderation/', MediaModerationView.as_view(), name='media-moderation'),
    path('media/moderation/<int:media_id>/', MediaModerateSingleView.as_view(), name='media-moderate-single'),
    path('media/moderation/bulk/', MediaBulkModerationView.as_view(), name='media-moderation-bulk'),
    path('media/moderation/detect-faces/', MediaDetectFacesView.as_view(), name='media-detect-faces'),
    path('media/moderation/delete-all-faces/', DeleteAllFacesView.as_view(), name='delete-all-faces'),
    path('media/<int:media_id>/file/', MediaFileView.as_view(), name='media-file'),
    path('media/public/', PublicMediaListView.as_view(), name='media-public'),
    path('users/public/', PublicUserListView.as_view(), name='public-user-list'),
    path('users/public/<int:user_id>/', PublicUserDetailView.as_view(), name='public-user-detail'),
    path('users/<int:user_id>/profile-picture/', UserProfilePictureView.as_view(), name='user-profile-picture'),
    path('admin/dashboard/', AdminDashboardView.as_view(), name='admin-dashboard'),
    path('admin/settings/', AdminSettingsView.as_view(), name='admin-settings'),
    path('admin/users/', AdminUserListView.as_view(), name='admin-user-list'),
    path('admin/users/bulk/', AdminUserBulkUpdateView.as_view(), name='admin-users-bulk-update'),
    path('admin/users/<int:user_id>/', AdminUserDetailView.as_view(), name='admin-user-detail'),
    path('admin/users/<int:user_id>/toggle-staff/', AdminUserToggleStaffView.as_view(), name='admin-user-toggle-staff'),
    path('admin/facetags/', FaceTagListView.as_view(), name='facetag-list'),
    path('admin/facetags/<int:tag_id>/', FaceTagDetailView.as_view(), name='facetag-detail'),
    path('face-groups/', FaceGroupListView.as_view(), name='face-group-list'),
    path('cookie-consent/', CookieConsentView.as_view(), name='cookie-consent'),
]
