# Generated by Django 5.0.14 on 2026-05-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_cookieconsent_user'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='failedattempt',
            new_name='users_faile_ip_addr_9b6486_idx',
            old_name='users_fail_ip_endpoi_idx',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='facetag',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
