# Generated by Django 5.0.14 on 2026-05-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rename_users_fail_ip_endpoi_idx_users_faile_ip_addr_9b6486_idx_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='media',
            constraint=models.UniqueConstraint(condition=models.Q(('content_hash__isnull', False)), fields=('user', 'content_hash'), name='unique_user_content_hash'),
        ),
    ]
