# Generated by Django 5.0.14 on 2026-05-15 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_unique_facetag_media_group'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='facetag',
            name='unique_media_face_group',
        ),
    ]
