# Generated by Django 5.0.14 on 2026-05-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_facetag_unique_media_face_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='similarity_position',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
